### ISSUE TITLE
Macaroons structure and caveats

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/warp10-macaroons-plugin#1]
The goal of the plugin is to craft `ReadTokens` or `WriteTokens`, as stated in https://github.com/cityzendata/warp10-platform/issues/280
# Token properties

A token (`Read` or `Write`) has the following common properties:

- `appName` (String)
- `producerUID` (String),
- `ttl` (Int, ms)
- `labels` (Map[String,String], not mandatory)

Additionally, a `WriteToken` has

- `ownerUID` (can be the same as `producerUID`)
- `indices` (List[Long], I don't know what it's used for, it's not exposed in any `deliverWriteToken` variant)

Additionally a `ReadToken` has

- `owners` (List[String])
- `producers` (List[String])
- `apps` (List[String])
- `hooks` (Map[String,String])

# Macaroons structure

Since the authentication plugin interface works by transforming arbitrary tokens into warp10 tokens,
it will be quite hard to really use macaroons as they're intended, and we'll need to rely on caveats
inspection, which is unfortunate. However, it should be feasible.

I don't think supporting all tokens features is necessary for now.
For owners / producers / apps, I don't think having a root macaroon which allows setting any of them
is a good idea. For now I think it's best we only rely on the couple `(app,producer)` that's in the identifier.

## Identifier

Since every token is identified by the couple `(appName,producerUID)`, I think that pair can be the identifier.

## Location

The location can be the warp10 cluster location

### Read / Write

`type=read` or `type=write`

### TTL

We take the smallest ttl caveat (and trigger a failure if none is given)

### Labels

For a `WriteToken`, we take the **union** of all labels caveats.
For a `ReadToken`, we take the **union** of all labels caveats.

## Examples

```
location https://warp10.example.org/
identifier app_name:producerUID
time < 1523546751000
signature <signature>
```

Would give

```
ReadToken(
  appName = app_name,
  producerUID = producerUID,
  ttl = 1523546751
)

WriteToken(
  appName = app_name,
  producerUID = producerUID,
  ttl = 1523546751
)
```

### Labels

```
location https://warp10.example.org/
identifier app_name:producerUID
time < 1523546751000
label=host=my-host
label=owner=my-owner
signature <signature>
```

Would give

```
ReadToken(
  appName = "app_name",
  producerUID = "producerUID",
  ttl = 1523546751,
  labels = Map("host" -> "my-host", "owner" -> "my-owner")
)

WriteToken(
  appName = app_name,
  producerUID = producerUID,
  ttl = 1523546751,
  labels = Map("host" -> "my-host", "owner" -> "my-owner")
)
```

**Comment by waxzce** [comment]
Do it will be to add more granularity on which series are query? Or it will not fit the plugin scope?

**Comment by divarvel** [comment]
What kind of granularity are you thinking of? In addition to app / producer
/ owner, labels are the primary means of fine-grained access control

**Comment by waxzce** [comment]
regexp caveat on series name ?

**Comment by divarvel** [comment]
There's no way to encode that in tokens (except with hooks), and that's not
a use case that occurred

**Comment by urcadox** [comment]
I agree with most everything, though I'm not too sure with using union or intersection for the labels caveat depending if we're generating a write or read token.

Could you maybe add an example that would make sense of this?

By the way, a caveat is missing: the read / write capability (which may or may not be linked to my incomprehension of the union / intersection issue I guess).

**Comment by divarvel** [comment]
Right, I did not consider a read/write macaroon.
I'll document a few examples that's a great idea.

**Comment by divarvel** [comment]
For labels it's always union, both for read and write tokens, as all labels have to be matched for read tokens, and all labels are added on a write token.

I've added a type caveat to restrict the kind of tokens we can generate.

Thinking about it, the first step will be to generate the token properties, then use them to validate the macaroon, so this will prevent logic mistakes and make sure we're not too far from the macaroons philosophy.

**Comment by waxzce** [comment]
Impplementation may differ or not, but it will be ready soon
