### ISSUE TITLE
Token Expiration copy from macaroon

### ISSUE THREAD

**Issue by waxzce** [CleverCloud/warp10-macaroons-plugin#18]
If the macaroon has no expiration, what is the best idea?
* Add no expiration to the warp10 token
* Add a year-long expiration time automatically 

It's for non-expiring token, considering that non-expiring token is A BAD IDEA.

**Comment by waxzce** [comment]
What do you think @hls ?

**Comment by waxzce** [comment]
What do you think @hbs ? @stevenLeroux ? @d33d33 ?

**Comment by hbs** [comment]
Do you always have a creation date in the macaroon? If yes then you can have a configuration parameter for you plugin which will determine until when you accept the tokens from the macaroons.

Non expiring tokens are not a problem if you have a way of revoking them on the Warp 10 side.

**Comment by waxzce** [comment]
There is a revocation list mechanism, I will implement and provide an extensibility solution ;-) (from simple file to ZK storage)

**Comment by waxzce** [comment]
Macaroon does not have a mandatory creation date, it's a good mechanism, but poorly tooled when it comes to syntax and common naming...

**Comment by waxzce** [comment]
Thanks a lot for the answer
